<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3B5I3LU" name="test.java.com.automation.practice.APtests" tests="1" failures="0" timestamp="20 Oct 2016 17:07:26 GMT" time="0.000" errors="1">
  <testcase name="CreateAccountWithWrongPostalCode" time="0.000" classname="test.java.com.automation.practice.APtests">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at test.java.com.autoPractice.TestBase.getLogger(TestBase.java:44)
	at main.java.com.framework.TestListener.getLogger(TestListener.java:74)
	at main.java.com.framework.TestListener.onTestStart(TestListener.java:30)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1700)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1675)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:619)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- CreateAccountWithWrongPostalCode -->
</testsuite> <!-- test.java.com.automation.practice.APtests -->
